name: 🐞 Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
    - octocat
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this bug report!
    - type: input
      id: contact
      attributes:
          label: Contact Details
          description: How can we get in touch with you if we need more info?
          placeholder: ex. email@example.com
      validations:
          required: false
    - type: textarea
      id: what-happened
      attributes:
          label: What happened?
          description: |
              Also tell us, what did you expect to happen?

              Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
          placeholder: Tell us what you see! Also add Image
          #   value: "A bug happened!"
      validations:
          required: true

    - type: textarea
      id: reproduce
      attributes:
          label: Steps to Reproduce?
          description: Also tell us, how to reproduce the issue?
          placeholder: |
              1. Go to
              2. Click on
              3. Scroll down to
              4. See error
          #   value: "A bug happened!"
      validations:
          required: true

    - type: dropdown
      id: version
      attributes:
          label: Version
          description: What version of our software are you running?
          options:
              - master
              - develop
      validations:
          required: true
    - type: dropdown
      id: browsers
      attributes:
          label: What browsers are you seeing the problem on?
          multiple: true
          options:
              - Firefox
              - Chrome
              - Safari
              - Microsoft Edge
    - type: textarea
      id: logs
      attributes:
          label: Relevant log output
          description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
          render: Shell

    - type: textarea
      attributes:
          label: Anything else?
          description: |
              Links? References? Anything that will give us more context about the issue you are encountering!

              Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.

    - type: checkboxes
      id: terms
      attributes:
          label: Code of Conduct
          description: By submitting this issue, you agree to follow our [Code of Conduct](https://www.lllorigins.com)
          options:
              - label: I agree to follow this project's Code of Conduct
                required: true
